In [3]:
import pandas as pd

csv_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTTo2JeAZm0NI2-ct-_qaH-lmDFaV77cmGAqY_rYwnClJGaFYkcLUZHVQ06UF2u_aRQ_BK3vZGkVLQ5/pub?gid=524884482&single=true&output=csv'

In [4]:
df = pd.read_csv(csv_url)

## The companies commited to climate change list

In [5]:
df

,Company name,ISIN,LEI,Location,Region,Sector,Organization type,Action,Commitment type,Commitment deadline,...,Type,Sub-type,Target classification,Base year,Target year,Year type,Date published,Near-term status,Net-zero status,BA15 status
0,AcBel Polytech Inc.,TW0006282007,254900BQVM5V0IY7RQ62,"Taiwan, Province of China",Asia,Technology Hardware and Equipment,Company,Target,NaN,NaN,...,Absolute,Reduction,1.5°C,2021.0,2030.0,CY,2023-06-15,Targets set,NaN,NaN
1,AcBel Polytech Inc.,TW0006282007,254900BQVM5V0IY7RQ62,"Taiwan, Province of China",Asia,Technology Hardware and Equipment,Company,Target,NaN,NaN,...,Intensity,Reduction,NaN,2021.0,2030.0,CY,2023-06-15,Targets set,NaN,NaN
2,Chalhoub Group,NaN,NaN,United Arab Emirates,MENA,Retailing,Company,Target,NaN,NaN,...,Absolute,Reduction,1.5°C,2021.0,2032.0,CY,2023-06-08,Targets set,NaN,NaN
3,Chalhoub Group,NaN,NaN,United Arab Emirates,MENA,Retailing,Company,Target,NaN,NaN,...,Absolute,Reduction,NaN,2021.0,2032.0,CY,2023-06-08,Targets set,NaN,NaN
4,Citrosuco Agroindustria S.A.,Not applicable,549300YLZY1O51E6VK62,Brazil,Latin America and the Caribbean,Food and Beverage Processing,Company,Target,NaN,NaN,...,Absolute,Reduction,Well-below 2°C,2019.0,2030.0,CY,2023-06-15,Targets set,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11713,GALVANICA FORMELLI SRL E MAGUI SRL,NaN,NaN,Italy,Europe,Chemicals,SME,Target,NaN,NaN,...,Absolute,Reduction,1.5°C,2022.0,2030.0,CY,2023-08-10,Targets set,NaN,NaN
11714,ZETA CATENE SRL,NaN,NaN,Italy,Europe,"Textiles, Apparel, Footwear and Luxury Goods",SME,Target,NaN,NaN,...,Absolute,Reduction,1.5°C,2022.0,2030.0,CY,2023-08-10,Targets set,NaN,NaN
11715,"EIKODO HOLDINGS Co., Ltd.",NaN,NaN,Japan,Asia,Food and Beverage Processing,SME,Target,NaN,NaN,...,Absolute,Reduction,1.5°C,2022.0,2030.0,CY,2023-08-10,Targets set,NaN,NaN
11716,N3 Group AS,NaN,NaN,Norway,Europe,"Trading Companies and Distributors, and Commer...",SME,Target,NaN,NaN,...,Absolute,Reduction,1.5°C,2020.0,2030.0,CY,2023-08-10,Targets set,NaN,NaN
11717,Technetix Ltd,NaN,NaN,United Kingdom,Europe,Technology Hardware and Equipment,SME,Target,NaN,NaN,...,Absolute,Reduction,1.5°C,2019.0,2030.0,CY,2023-08-10,Targets set,NaN,NaN

In [7]:
companies_by_regions = df['Region '].value_counts()
companies_by_regions

Region
Europe                             6791
Asia                               2541
Northern America                   1718
Latin America and the Caribbean     273
Oceania                             258
Africa                               97
MENA                                 39
Name: count, dtype: int64

In [8]:
companies_by_locations = df['Location'].value_counts()
companies_by_locations

Location
United Kingdom              2166
United States of America    1510
Japan                       1012
Germany                      671
France                       667
                            ...
Croatia                        1
Albania                        1
Nigeria                        1
Macau, Province of China       1
Lebanon                        1
Name: count, Length: 88, dtype: int64

## Question

How could we get some geolocation based on the Location and Region. In this way we could plot all companies in map in a way we could visualize all commitments in the globe, perhaps we could see which regions have more companies.